### ISSUE TITLE
AttributeError on IronPython 2.7.5

### ISSUE THREAD

**Issue by utgwkk** [nedbat/coveragepy#26]
I tried using coveragepy on IronPython 2.7.5 and got following backtrace:

```
> ipy -m coverage run TestRunner.py
C:\Program Files (x86)\IronPython 2.7\lib\site-packages\coverage\cmdline.py:1: DeprecationWarning: object.__new__() takes no parameters
  # Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 175, in run_module
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\coverage\cmdline.py", line 483, in command_line
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 81, in _run_module_code
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 72, in _run_code
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\coverage\__main__.py", line 8, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\coverage\cmdline.py", line 753, in main
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\coverage\cmdline.py", line 623, in do_run
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\coverage\control.py", line 662, in start
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\coverage\collector.py", line 302, in start
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\coverage\pytracer.py", line 89, in _trace
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\coverage\control.py", line 564, in _should_trace
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\coverage\control.py", line 432, in _should_trace_internal
AttributeError: 'NoneType' object has no attribute 'get'
```

The version of module is `version 4.3.4 without C extension`.

**Comment by nedbat** [comment]
I've never tried running coverage.py with IronPython.  Looks like there will be some work needed to support it.

**Comment by nedbat** [comment]
OK, as of https://bitbucket.org/ned/coveragepy/commits/0a62a90018ba95368212f8ae1c4e0c6645f6165f (GitHub: https://github.com/nedbat/coveragepy/commit/13ed869c6be652f0b7729cebb26583d03c7ab12a), IronPython can do `coverage run`, at least for the simple program I tried. 

Some things probably won't work properly, because of these IronPython bugs:
https://github.com/IronLanguages/main/issues/1296 and https://github.com/IronLanguages/main/issues/1518
