### ISSUE TITLE
Pipy install fails with xmlrpc error

### ISSUE THREAD

**Issue by quazgar** [nedbat/coveragepy#50]
Possibly some malformed content? `pip3 search coverage` fails with:

    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/usr/lib/python3/dist-packages/pip/commands/search.py", line 45, in run
        pypi_hits = self.search(query, options)
      File "/usr/lib/python3/dist-packages/pip/commands/search.py", line 62, in search
        hits = pypi.search({'name': query, 'summary': query}, 'or')
      File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
        return self.__send(self.__name, args)
      File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request
        verbose=self.__verbose
      File "/usr/lib/python3/dist-packages/pip/download.py", line 778, in request
        return self.parse_response(response.raw)
      File "/usr/lib/python3.6/xmlrpc/client.py", line 1342, in parse_response
        return u.close()
      File "/usr/lib/python3.6/xmlrpc/client.py", line 656, in close
        raise Fault(**self._stack[0])
    xmlrpc.client.Fault: <Fault -32500: 'application error'>

**Comment by nedbat** [comment]
Hmm, weird. I've asked on the pip tracker: https://github.com/pypa/pip/issues/5414
